/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as SiteIndexRouteImport } from './routes/_site/index'
import { Route as SiteVerifyEmailRouteImport } from './routes/_site/verify-email'
import { Route as SiteStoresRouteImport } from './routes/_site/stores'
import { Route as SiteSearchRouteImport } from './routes/_site/search'
import { Route as SiteResetPasswordRouteImport } from './routes/_site/reset-password'
import { Route as SiteRegisterRouteImport } from './routes/_site/register'
import { Route as SitePromotionsRouteImport } from './routes/_site/promotions'
import { Route as SitePaymentResultRouteImport } from './routes/_site/payment-result'
import { Route as SiteNewsRouteImport } from './routes/_site/news'
import { Route as SiteMerchantRouteImport } from './routes/_site/merchant'
import { Route as SiteLoginRouteImport } from './routes/_site/login'
import { Route as SiteForgotPasswordRouteImport } from './routes/_site/forgot-password'
import { Route as SiteFlashSaleRouteImport } from './routes/_site/flash-sale'
import { Route as SiteContactRouteImport } from './routes/_site/contact'
import { Route as SiteCheckoutSuccessRouteImport } from './routes/_site/checkout-success'
import { Route as SiteCheckoutRouteImport } from './routes/_site/checkout'
import { Route as SiteCartRouteImport } from './routes/_site/cart'
import { Route as SiteAdminRouteImport } from './routes/_site/admin'
import { Route as SiteAccountRouteImport } from './routes/_site/account'
import { Route as SiteAboutRouteImport } from './routes/_site/about'
import { Route as SiteTrackOrderIndexRouteImport } from './routes/_site/track-order.index'
import { Route as SiteAdminIndexRouteImport } from './routes/_site/admin/index'
import { Route as SiteAccountIndexRouteImport } from './routes/_site/account/index'
import { Route as SiteTrackOrderOrderIdRouteImport } from './routes/_site/track-order.$orderId'
import { Route as SiteStoreIdRouteImport } from './routes/_site/store.$id'
import { Route as SiteProductIdRouteImport } from './routes/_site/product.$id'
import { Route as SitePoliciesSlugRouteImport } from './routes/_site/policies.$slug'
import { Route as SiteNewsIdRouteImport } from './routes/_site/news_.$id'
import { Route as SiteMerchantWarrantiesRouteImport } from './routes/_site/merchant/warranties'
import { Route as SiteMerchantVouchersRouteImport } from './routes/_site/merchant/vouchers'
import { Route as SiteMerchantStaffRouteImport } from './routes/_site/merchant/staff'
import { Route as SiteMerchantProductsRouteImport } from './routes/_site/merchant/products'
import { Route as SiteMerchantOrdersRouteImport } from './routes/_site/merchant/orders'
import { Route as SiteMerchantInventoryRouteImport } from './routes/_site/merchant/inventory'
import { Route as SiteMerchantFlashSalesRouteImport } from './routes/_site/merchant/flash-sales'
import { Route as SiteMerchantDashboardRouteImport } from './routes/_site/merchant/dashboard'
import { Route as SiteMerchantCategoriesRouteImport } from './routes/_site/merchant/categories'
import { Route as SiteMerchantBrandsRouteImport } from './routes/_site/merchant/brands'
import { Route as SiteCategorySlugRouteImport } from './routes/_site/category.$slug'
import { Route as SiteAdminWarrantiesRouteImport } from './routes/_site/admin/warranties'
import { Route as SiteAdminVouchersRouteImport } from './routes/_site/admin/vouchers'
import { Route as SiteAdminUsersRouteImport } from './routes/_site/admin/users'
import { Route as SiteAdminStoresRouteImport } from './routes/_site/admin/stores'
import { Route as SiteAdminStatsRouteImport } from './routes/_site/admin/stats'
import { Route as SiteAdminShippersRouteImport } from './routes/_site/admin/shippers'
import { Route as SiteAdminReviewsRouteImport } from './routes/_site/admin/reviews'
import { Route as SiteAdminProductsRouteImport } from './routes/_site/admin/products'
import { Route as SiteAdminOrdersRouteImport } from './routes/_site/admin/orders'
import { Route as SiteAdminNewsRouteImport } from './routes/_site/admin/news'
import { Route as SiteAdminFlashSalesRouteImport } from './routes/_site/admin/flash-sales'
import { Route as SiteAdminChatbotHistoryRouteImport } from './routes/_site/admin/chatbot-history'
import { Route as SiteAdminCategoriesRouteImport } from './routes/_site/admin/categories'
import { Route as SiteAdminBrandsRouteImport } from './routes/_site/admin/brands'
import { Route as SiteAdminBannersRouteImport } from './routes/_site/admin/banners'
import { Route as SiteAccountWishlistRouteImport } from './routes/_site/account/wishlist'
import { Route as SiteAccountOrdersRouteImport } from './routes/_site/account/orders'
import { Route as SiteAccountNotificationsRouteImport } from './routes/_site/account/notifications'
import { Route as SiteAccountAddressesRouteImport } from './routes/_site/account/addresses'

const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteVerifyEmailRoute = SiteVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => SiteRoute,
} as any)
const SiteStoresRoute = SiteStoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => SiteRoute,
} as any)
const SiteSearchRoute = SiteSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => SiteRoute,
} as any)
const SiteResetPasswordRoute = SiteResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => SiteRoute,
} as any)
const SiteRegisterRoute = SiteRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => SiteRoute,
} as any)
const SitePromotionsRoute = SitePromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => SiteRoute,
} as any)
const SitePaymentResultRoute = SitePaymentResultRouteImport.update({
  id: '/payment-result',
  path: '/payment-result',
  getParentRoute: () => SiteRoute,
} as any)
const SiteNewsRoute = SiteNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => SiteRoute,
} as any)
const SiteMerchantRoute = SiteMerchantRouteImport.update({
  id: '/merchant',
  path: '/merchant',
  getParentRoute: () => SiteRoute,
} as any)
const SiteLoginRoute = SiteLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => SiteRoute,
} as any)
const SiteForgotPasswordRoute = SiteForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => SiteRoute,
} as any)
const SiteFlashSaleRoute = SiteFlashSaleRouteImport.update({
  id: '/flash-sale',
  path: '/flash-sale',
  getParentRoute: () => SiteRoute,
} as any)
const SiteContactRoute = SiteContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => SiteRoute,
} as any)
const SiteCheckoutSuccessRoute = SiteCheckoutSuccessRouteImport.update({
  id: '/checkout-success',
  path: '/checkout-success',
  getParentRoute: () => SiteRoute,
} as any)
const SiteCheckoutRoute = SiteCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => SiteRoute,
} as any)
const SiteCartRoute = SiteCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAdminRoute = SiteAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAccountRoute = SiteAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAboutRoute = SiteAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SiteRoute,
} as any)
const SiteTrackOrderIndexRoute = SiteTrackOrderIndexRouteImport.update({
  id: '/track-order/',
  path: '/track-order/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAdminIndexRoute = SiteAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteAdminRoute,
} as any)
const SiteAccountIndexRoute = SiteAccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteAccountRoute,
} as any)
const SiteTrackOrderOrderIdRoute = SiteTrackOrderOrderIdRouteImport.update({
  id: '/track-order/$orderId',
  path: '/track-order/$orderId',
  getParentRoute: () => SiteRoute,
} as any)
const SiteStoreIdRoute = SiteStoreIdRouteImport.update({
  id: '/store/$id',
  path: '/store/$id',
  getParentRoute: () => SiteRoute,
} as any)
const SiteProductIdRoute = SiteProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => SiteRoute,
} as any)
const SitePoliciesSlugRoute = SitePoliciesSlugRouteImport.update({
  id: '/policies/$slug',
  path: '/policies/$slug',
  getParentRoute: () => SiteRoute,
} as any)
const SiteNewsIdRoute = SiteNewsIdRouteImport.update({
  id: '/news_/$id',
  path: '/news/$id',
  getParentRoute: () => SiteRoute,
} as any)
const SiteMerchantWarrantiesRoute = SiteMerchantWarrantiesRouteImport.update({
  id: '/warranties',
  path: '/warranties',
  getParentRoute: () => SiteMerchantRoute,
} as any)
const SiteMerchantVouchersRoute = SiteMerchantVouchersRouteImport.update({
  id: '/vouchers',
  path: '/vouchers',
  getParentRoute: () => SiteMerchantRoute,
} as any)
const SiteMerchantStaffRoute = SiteMerchantStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => SiteMerchantRoute,
} as any)
const SiteMerchantProductsRoute = SiteMerchantProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => SiteMerchantRoute,
} as any)
const SiteMerchantOrdersRoute = SiteMerchantOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => SiteMerchantRoute,
} as any)
const SiteMerchantInventoryRoute = SiteMerchantInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => SiteMerchantRoute,
} as any)
const SiteMerchantFlashSalesRoute = SiteMerchantFlashSalesRouteImport.update({
  id: '/flash-sales',
  path: '/flash-sales',
  getParentRoute: () => SiteMerchantRoute,
} as any)
const SiteMerchantDashboardRoute = SiteMerchantDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => SiteMerchantRoute,
} as any)
const SiteMerchantCategoriesRoute = SiteMerchantCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => SiteMerchantRoute,
} as any)
const SiteMerchantBrandsRoute = SiteMerchantBrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => SiteMerchantRoute,
} as any)
const SiteCategorySlugRoute = SiteCategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAdminWarrantiesRoute = SiteAdminWarrantiesRouteImport.update({
  id: '/warranties',
  path: '/warranties',
  getParentRoute: () => SiteAdminRoute,
} as any)
const SiteAdminVouchersRoute = SiteAdminVouchersRouteImport.update({
  id: '/vouchers',
  path: '/vouchers',
  getParentRoute: () => SiteAdminRoute,
} as any)
const SiteAdminUsersRoute = SiteAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => SiteAdminRoute,
} as any)
const SiteAdminStoresRoute = SiteAdminStoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => SiteAdminRoute,
} as any)
const SiteAdminStatsRoute = SiteAdminStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => SiteAdminRoute,
} as any)
const SiteAdminShippersRoute = SiteAdminShippersRouteImport.update({
  id: '/shippers',
  path: '/shippers',
  getParentRoute: () => SiteAdminRoute,
} as any)
const SiteAdminReviewsRoute = SiteAdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => SiteAdminRoute,
} as any)
const SiteAdminProductsRoute = SiteAdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => SiteAdminRoute,
} as any)
const SiteAdminOrdersRoute = SiteAdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => SiteAdminRoute,
} as any)
const SiteAdminNewsRoute = SiteAdminNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => SiteAdminRoute,
} as any)
const SiteAdminFlashSalesRoute = SiteAdminFlashSalesRouteImport.update({
  id: '/flash-sales',
  path: '/flash-sales',
  getParentRoute: () => SiteAdminRoute,
} as any)
const SiteAdminChatbotHistoryRoute = SiteAdminChatbotHistoryRouteImport.update({
  id: '/chatbot-history',
  path: '/chatbot-history',
  getParentRoute: () => SiteAdminRoute,
} as any)
const SiteAdminCategoriesRoute = SiteAdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => SiteAdminRoute,
} as any)
const SiteAdminBrandsRoute = SiteAdminBrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => SiteAdminRoute,
} as any)
const SiteAdminBannersRoute = SiteAdminBannersRouteImport.update({
  id: '/banners',
  path: '/banners',
  getParentRoute: () => SiteAdminRoute,
} as any)
const SiteAccountWishlistRoute = SiteAccountWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => SiteAccountRoute,
} as any)
const SiteAccountOrdersRoute = SiteAccountOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => SiteAccountRoute,
} as any)
const SiteAccountNotificationsRoute =
  SiteAccountNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => SiteAccountRoute,
  } as any)
const SiteAccountAddressesRoute = SiteAccountAddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => SiteAccountRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/about': typeof SiteAboutRoute
  '/account': typeof SiteAccountRouteWithChildren
  '/admin': typeof SiteAdminRouteWithChildren
  '/cart': typeof SiteCartRoute
  '/checkout': typeof SiteCheckoutRoute
  '/checkout-success': typeof SiteCheckoutSuccessRoute
  '/contact': typeof SiteContactRoute
  '/flash-sale': typeof SiteFlashSaleRoute
  '/forgot-password': typeof SiteForgotPasswordRoute
  '/login': typeof SiteLoginRoute
  '/merchant': typeof SiteMerchantRouteWithChildren
  '/news': typeof SiteNewsRoute
  '/payment-result': typeof SitePaymentResultRoute
  '/promotions': typeof SitePromotionsRoute
  '/register': typeof SiteRegisterRoute
  '/reset-password': typeof SiteResetPasswordRoute
  '/search': typeof SiteSearchRoute
  '/stores': typeof SiteStoresRoute
  '/verify-email': typeof SiteVerifyEmailRoute
  '/account/addresses': typeof SiteAccountAddressesRoute
  '/account/notifications': typeof SiteAccountNotificationsRoute
  '/account/orders': typeof SiteAccountOrdersRoute
  '/account/wishlist': typeof SiteAccountWishlistRoute
  '/admin/banners': typeof SiteAdminBannersRoute
  '/admin/brands': typeof SiteAdminBrandsRoute
  '/admin/categories': typeof SiteAdminCategoriesRoute
  '/admin/chatbot-history': typeof SiteAdminChatbotHistoryRoute
  '/admin/flash-sales': typeof SiteAdminFlashSalesRoute
  '/admin/news': typeof SiteAdminNewsRoute
  '/admin/orders': typeof SiteAdminOrdersRoute
  '/admin/products': typeof SiteAdminProductsRoute
  '/admin/reviews': typeof SiteAdminReviewsRoute
  '/admin/shippers': typeof SiteAdminShippersRoute
  '/admin/stats': typeof SiteAdminStatsRoute
  '/admin/stores': typeof SiteAdminStoresRoute
  '/admin/users': typeof SiteAdminUsersRoute
  '/admin/vouchers': typeof SiteAdminVouchersRoute
  '/admin/warranties': typeof SiteAdminWarrantiesRoute
  '/category/$slug': typeof SiteCategorySlugRoute
  '/merchant/brands': typeof SiteMerchantBrandsRoute
  '/merchant/categories': typeof SiteMerchantCategoriesRoute
  '/merchant/dashboard': typeof SiteMerchantDashboardRoute
  '/merchant/flash-sales': typeof SiteMerchantFlashSalesRoute
  '/merchant/inventory': typeof SiteMerchantInventoryRoute
  '/merchant/orders': typeof SiteMerchantOrdersRoute
  '/merchant/products': typeof SiteMerchantProductsRoute
  '/merchant/staff': typeof SiteMerchantStaffRoute
  '/merchant/vouchers': typeof SiteMerchantVouchersRoute
  '/merchant/warranties': typeof SiteMerchantWarrantiesRoute
  '/news/$id': typeof SiteNewsIdRoute
  '/policies/$slug': typeof SitePoliciesSlugRoute
  '/product/$id': typeof SiteProductIdRoute
  '/store/$id': typeof SiteStoreIdRoute
  '/track-order/$orderId': typeof SiteTrackOrderOrderIdRoute
  '/account/': typeof SiteAccountIndexRoute
  '/admin/': typeof SiteAdminIndexRoute
  '/track-order/': typeof SiteTrackOrderIndexRoute
}
export interface FileRoutesByTo {
  '/about': typeof SiteAboutRoute
  '/cart': typeof SiteCartRoute
  '/checkout': typeof SiteCheckoutRoute
  '/checkout-success': typeof SiteCheckoutSuccessRoute
  '/contact': typeof SiteContactRoute
  '/flash-sale': typeof SiteFlashSaleRoute
  '/forgot-password': typeof SiteForgotPasswordRoute
  '/login': typeof SiteLoginRoute
  '/merchant': typeof SiteMerchantRouteWithChildren
  '/news': typeof SiteNewsRoute
  '/payment-result': typeof SitePaymentResultRoute
  '/promotions': typeof SitePromotionsRoute
  '/register': typeof SiteRegisterRoute
  '/reset-password': typeof SiteResetPasswordRoute
  '/search': typeof SiteSearchRoute
  '/stores': typeof SiteStoresRoute
  '/verify-email': typeof SiteVerifyEmailRoute
  '/': typeof SiteIndexRoute
  '/account/addresses': typeof SiteAccountAddressesRoute
  '/account/notifications': typeof SiteAccountNotificationsRoute
  '/account/orders': typeof SiteAccountOrdersRoute
  '/account/wishlist': typeof SiteAccountWishlistRoute
  '/admin/banners': typeof SiteAdminBannersRoute
  '/admin/brands': typeof SiteAdminBrandsRoute
  '/admin/categories': typeof SiteAdminCategoriesRoute
  '/admin/chatbot-history': typeof SiteAdminChatbotHistoryRoute
  '/admin/flash-sales': typeof SiteAdminFlashSalesRoute
  '/admin/news': typeof SiteAdminNewsRoute
  '/admin/orders': typeof SiteAdminOrdersRoute
  '/admin/products': typeof SiteAdminProductsRoute
  '/admin/reviews': typeof SiteAdminReviewsRoute
  '/admin/shippers': typeof SiteAdminShippersRoute
  '/admin/stats': typeof SiteAdminStatsRoute
  '/admin/stores': typeof SiteAdminStoresRoute
  '/admin/users': typeof SiteAdminUsersRoute
  '/admin/vouchers': typeof SiteAdminVouchersRoute
  '/admin/warranties': typeof SiteAdminWarrantiesRoute
  '/category/$slug': typeof SiteCategorySlugRoute
  '/merchant/brands': typeof SiteMerchantBrandsRoute
  '/merchant/categories': typeof SiteMerchantCategoriesRoute
  '/merchant/dashboard': typeof SiteMerchantDashboardRoute
  '/merchant/flash-sales': typeof SiteMerchantFlashSalesRoute
  '/merchant/inventory': typeof SiteMerchantInventoryRoute
  '/merchant/orders': typeof SiteMerchantOrdersRoute
  '/merchant/products': typeof SiteMerchantProductsRoute
  '/merchant/staff': typeof SiteMerchantStaffRoute
  '/merchant/vouchers': typeof SiteMerchantVouchersRoute
  '/merchant/warranties': typeof SiteMerchantWarrantiesRoute
  '/news/$id': typeof SiteNewsIdRoute
  '/policies/$slug': typeof SitePoliciesSlugRoute
  '/product/$id': typeof SiteProductIdRoute
  '/store/$id': typeof SiteStoreIdRoute
  '/track-order/$orderId': typeof SiteTrackOrderOrderIdRoute
  '/account': typeof SiteAccountIndexRoute
  '/admin': typeof SiteAdminIndexRoute
  '/track-order': typeof SiteTrackOrderIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteWithChildren
  '/_site/about': typeof SiteAboutRoute
  '/_site/account': typeof SiteAccountRouteWithChildren
  '/_site/admin': typeof SiteAdminRouteWithChildren
  '/_site/cart': typeof SiteCartRoute
  '/_site/checkout': typeof SiteCheckoutRoute
  '/_site/checkout-success': typeof SiteCheckoutSuccessRoute
  '/_site/contact': typeof SiteContactRoute
  '/_site/flash-sale': typeof SiteFlashSaleRoute
  '/_site/forgot-password': typeof SiteForgotPasswordRoute
  '/_site/login': typeof SiteLoginRoute
  '/_site/merchant': typeof SiteMerchantRouteWithChildren
  '/_site/news': typeof SiteNewsRoute
  '/_site/payment-result': typeof SitePaymentResultRoute
  '/_site/promotions': typeof SitePromotionsRoute
  '/_site/register': typeof SiteRegisterRoute
  '/_site/reset-password': typeof SiteResetPasswordRoute
  '/_site/search': typeof SiteSearchRoute
  '/_site/stores': typeof SiteStoresRoute
  '/_site/verify-email': typeof SiteVerifyEmailRoute
  '/_site/': typeof SiteIndexRoute
  '/_site/account/addresses': typeof SiteAccountAddressesRoute
  '/_site/account/notifications': typeof SiteAccountNotificationsRoute
  '/_site/account/orders': typeof SiteAccountOrdersRoute
  '/_site/account/wishlist': typeof SiteAccountWishlistRoute
  '/_site/admin/banners': typeof SiteAdminBannersRoute
  '/_site/admin/brands': typeof SiteAdminBrandsRoute
  '/_site/admin/categories': typeof SiteAdminCategoriesRoute
  '/_site/admin/chatbot-history': typeof SiteAdminChatbotHistoryRoute
  '/_site/admin/flash-sales': typeof SiteAdminFlashSalesRoute
  '/_site/admin/news': typeof SiteAdminNewsRoute
  '/_site/admin/orders': typeof SiteAdminOrdersRoute
  '/_site/admin/products': typeof SiteAdminProductsRoute
  '/_site/admin/reviews': typeof SiteAdminReviewsRoute
  '/_site/admin/shippers': typeof SiteAdminShippersRoute
  '/_site/admin/stats': typeof SiteAdminStatsRoute
  '/_site/admin/stores': typeof SiteAdminStoresRoute
  '/_site/admin/users': typeof SiteAdminUsersRoute
  '/_site/admin/vouchers': typeof SiteAdminVouchersRoute
  '/_site/admin/warranties': typeof SiteAdminWarrantiesRoute
  '/_site/category/$slug': typeof SiteCategorySlugRoute
  '/_site/merchant/brands': typeof SiteMerchantBrandsRoute
  '/_site/merchant/categories': typeof SiteMerchantCategoriesRoute
  '/_site/merchant/dashboard': typeof SiteMerchantDashboardRoute
  '/_site/merchant/flash-sales': typeof SiteMerchantFlashSalesRoute
  '/_site/merchant/inventory': typeof SiteMerchantInventoryRoute
  '/_site/merchant/orders': typeof SiteMerchantOrdersRoute
  '/_site/merchant/products': typeof SiteMerchantProductsRoute
  '/_site/merchant/staff': typeof SiteMerchantStaffRoute
  '/_site/merchant/vouchers': typeof SiteMerchantVouchersRoute
  '/_site/merchant/warranties': typeof SiteMerchantWarrantiesRoute
  '/_site/news_/$id': typeof SiteNewsIdRoute
  '/_site/policies/$slug': typeof SitePoliciesSlugRoute
  '/_site/product/$id': typeof SiteProductIdRoute
  '/_site/store/$id': typeof SiteStoreIdRoute
  '/_site/track-order/$orderId': typeof SiteTrackOrderOrderIdRoute
  '/_site/account/': typeof SiteAccountIndexRoute
  '/_site/admin/': typeof SiteAdminIndexRoute
  '/_site/track-order/': typeof SiteTrackOrderIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/checkout-success'
    | '/contact'
    | '/flash-sale'
    | '/forgot-password'
    | '/login'
    | '/merchant'
    | '/news'
    | '/payment-result'
    | '/promotions'
    | '/register'
    | '/reset-password'
    | '/search'
    | '/stores'
    | '/verify-email'
    | '/account/addresses'
    | '/account/notifications'
    | '/account/orders'
    | '/account/wishlist'
    | '/admin/banners'
    | '/admin/brands'
    | '/admin/categories'
    | '/admin/chatbot-history'
    | '/admin/flash-sales'
    | '/admin/news'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/reviews'
    | '/admin/shippers'
    | '/admin/stats'
    | '/admin/stores'
    | '/admin/users'
    | '/admin/vouchers'
    | '/admin/warranties'
    | '/category/$slug'
    | '/merchant/brands'
    | '/merchant/categories'
    | '/merchant/dashboard'
    | '/merchant/flash-sales'
    | '/merchant/inventory'
    | '/merchant/orders'
    | '/merchant/products'
    | '/merchant/staff'
    | '/merchant/vouchers'
    | '/merchant/warranties'
    | '/news/$id'
    | '/policies/$slug'
    | '/product/$id'
    | '/store/$id'
    | '/track-order/$orderId'
    | '/account/'
    | '/admin/'
    | '/track-order/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/cart'
    | '/checkout'
    | '/checkout-success'
    | '/contact'
    | '/flash-sale'
    | '/forgot-password'
    | '/login'
    | '/merchant'
    | '/news'
    | '/payment-result'
    | '/promotions'
    | '/register'
    | '/reset-password'
    | '/search'
    | '/stores'
    | '/verify-email'
    | '/'
    | '/account/addresses'
    | '/account/notifications'
    | '/account/orders'
    | '/account/wishlist'
    | '/admin/banners'
    | '/admin/brands'
    | '/admin/categories'
    | '/admin/chatbot-history'
    | '/admin/flash-sales'
    | '/admin/news'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/reviews'
    | '/admin/shippers'
    | '/admin/stats'
    | '/admin/stores'
    | '/admin/users'
    | '/admin/vouchers'
    | '/admin/warranties'
    | '/category/$slug'
    | '/merchant/brands'
    | '/merchant/categories'
    | '/merchant/dashboard'
    | '/merchant/flash-sales'
    | '/merchant/inventory'
    | '/merchant/orders'
    | '/merchant/products'
    | '/merchant/staff'
    | '/merchant/vouchers'
    | '/merchant/warranties'
    | '/news/$id'
    | '/policies/$slug'
    | '/product/$id'
    | '/store/$id'
    | '/track-order/$orderId'
    | '/account'
    | '/admin'
    | '/track-order'
  id:
    | '__root__'
    | '/_site'
    | '/_site/about'
    | '/_site/account'
    | '/_site/admin'
    | '/_site/cart'
    | '/_site/checkout'
    | '/_site/checkout-success'
    | '/_site/contact'
    | '/_site/flash-sale'
    | '/_site/forgot-password'
    | '/_site/login'
    | '/_site/merchant'
    | '/_site/news'
    | '/_site/payment-result'
    | '/_site/promotions'
    | '/_site/register'
    | '/_site/reset-password'
    | '/_site/search'
    | '/_site/stores'
    | '/_site/verify-email'
    | '/_site/'
    | '/_site/account/addresses'
    | '/_site/account/notifications'
    | '/_site/account/orders'
    | '/_site/account/wishlist'
    | '/_site/admin/banners'
    | '/_site/admin/brands'
    | '/_site/admin/categories'
    | '/_site/admin/chatbot-history'
    | '/_site/admin/flash-sales'
    | '/_site/admin/news'
    | '/_site/admin/orders'
    | '/_site/admin/products'
    | '/_site/admin/reviews'
    | '/_site/admin/shippers'
    | '/_site/admin/stats'
    | '/_site/admin/stores'
    | '/_site/admin/users'
    | '/_site/admin/vouchers'
    | '/_site/admin/warranties'
    | '/_site/category/$slug'
    | '/_site/merchant/brands'
    | '/_site/merchant/categories'
    | '/_site/merchant/dashboard'
    | '/_site/merchant/flash-sales'
    | '/_site/merchant/inventory'
    | '/_site/merchant/orders'
    | '/_site/merchant/products'
    | '/_site/merchant/staff'
    | '/_site/merchant/vouchers'
    | '/_site/merchant/warranties'
    | '/_site/news_/$id'
    | '/_site/policies/$slug'
    | '/_site/product/$id'
    | '/_site/store/$id'
    | '/_site/track-order/$orderId'
    | '/_site/account/'
    | '/_site/admin/'
    | '/_site/track-order/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRoute: typeof SiteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/verify-email': {
      id: '/_site/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof SiteVerifyEmailRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/stores': {
      id: '/_site/stores'
      path: '/stores'
      fullPath: '/stores'
      preLoaderRoute: typeof SiteStoresRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/search': {
      id: '/_site/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SiteSearchRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/reset-password': {
      id: '/_site/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof SiteResetPasswordRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/register': {
      id: '/_site/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof SiteRegisterRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/promotions': {
      id: '/_site/promotions'
      path: '/promotions'
      fullPath: '/promotions'
      preLoaderRoute: typeof SitePromotionsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/payment-result': {
      id: '/_site/payment-result'
      path: '/payment-result'
      fullPath: '/payment-result'
      preLoaderRoute: typeof SitePaymentResultRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/news': {
      id: '/_site/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof SiteNewsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/merchant': {
      id: '/_site/merchant'
      path: '/merchant'
      fullPath: '/merchant'
      preLoaderRoute: typeof SiteMerchantRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/login': {
      id: '/_site/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof SiteLoginRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/forgot-password': {
      id: '/_site/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof SiteForgotPasswordRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/flash-sale': {
      id: '/_site/flash-sale'
      path: '/flash-sale'
      fullPath: '/flash-sale'
      preLoaderRoute: typeof SiteFlashSaleRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/contact': {
      id: '/_site/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof SiteContactRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/checkout-success': {
      id: '/_site/checkout-success'
      path: '/checkout-success'
      fullPath: '/checkout-success'
      preLoaderRoute: typeof SiteCheckoutSuccessRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/checkout': {
      id: '/_site/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof SiteCheckoutRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/cart': {
      id: '/_site/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof SiteCartRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/admin': {
      id: '/_site/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof SiteAdminRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/account': {
      id: '/_site/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof SiteAccountRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/about': {
      id: '/_site/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof SiteAboutRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/track-order/': {
      id: '/_site/track-order/'
      path: '/track-order'
      fullPath: '/track-order/'
      preLoaderRoute: typeof SiteTrackOrderIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/admin/': {
      id: '/_site/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof SiteAdminIndexRouteImport
      parentRoute: typeof SiteAdminRoute
    }
    '/_site/account/': {
      id: '/_site/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof SiteAccountIndexRouteImport
      parentRoute: typeof SiteAccountRoute
    }
    '/_site/track-order/$orderId': {
      id: '/_site/track-order/$orderId'
      path: '/track-order/$orderId'
      fullPath: '/track-order/$orderId'
      preLoaderRoute: typeof SiteTrackOrderOrderIdRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/store/$id': {
      id: '/_site/store/$id'
      path: '/store/$id'
      fullPath: '/store/$id'
      preLoaderRoute: typeof SiteStoreIdRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/product/$id': {
      id: '/_site/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof SiteProductIdRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/policies/$slug': {
      id: '/_site/policies/$slug'
      path: '/policies/$slug'
      fullPath: '/policies/$slug'
      preLoaderRoute: typeof SitePoliciesSlugRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/news_/$id': {
      id: '/_site/news_/$id'
      path: '/news/$id'
      fullPath: '/news/$id'
      preLoaderRoute: typeof SiteNewsIdRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/merchant/warranties': {
      id: '/_site/merchant/warranties'
      path: '/warranties'
      fullPath: '/merchant/warranties'
      preLoaderRoute: typeof SiteMerchantWarrantiesRouteImport
      parentRoute: typeof SiteMerchantRoute
    }
    '/_site/merchant/vouchers': {
      id: '/_site/merchant/vouchers'
      path: '/vouchers'
      fullPath: '/merchant/vouchers'
      preLoaderRoute: typeof SiteMerchantVouchersRouteImport
      parentRoute: typeof SiteMerchantRoute
    }
    '/_site/merchant/staff': {
      id: '/_site/merchant/staff'
      path: '/staff'
      fullPath: '/merchant/staff'
      preLoaderRoute: typeof SiteMerchantStaffRouteImport
      parentRoute: typeof SiteMerchantRoute
    }
    '/_site/merchant/products': {
      id: '/_site/merchant/products'
      path: '/products'
      fullPath: '/merchant/products'
      preLoaderRoute: typeof SiteMerchantProductsRouteImport
      parentRoute: typeof SiteMerchantRoute
    }
    '/_site/merchant/orders': {
      id: '/_site/merchant/orders'
      path: '/orders'
      fullPath: '/merchant/orders'
      preLoaderRoute: typeof SiteMerchantOrdersRouteImport
      parentRoute: typeof SiteMerchantRoute
    }
    '/_site/merchant/inventory': {
      id: '/_site/merchant/inventory'
      path: '/inventory'
      fullPath: '/merchant/inventory'
      preLoaderRoute: typeof SiteMerchantInventoryRouteImport
      parentRoute: typeof SiteMerchantRoute
    }
    '/_site/merchant/flash-sales': {
      id: '/_site/merchant/flash-sales'
      path: '/flash-sales'
      fullPath: '/merchant/flash-sales'
      preLoaderRoute: typeof SiteMerchantFlashSalesRouteImport
      parentRoute: typeof SiteMerchantRoute
    }
    '/_site/merchant/dashboard': {
      id: '/_site/merchant/dashboard'
      path: '/dashboard'
      fullPath: '/merchant/dashboard'
      preLoaderRoute: typeof SiteMerchantDashboardRouteImport
      parentRoute: typeof SiteMerchantRoute
    }
    '/_site/merchant/categories': {
      id: '/_site/merchant/categories'
      path: '/categories'
      fullPath: '/merchant/categories'
      preLoaderRoute: typeof SiteMerchantCategoriesRouteImport
      parentRoute: typeof SiteMerchantRoute
    }
    '/_site/merchant/brands': {
      id: '/_site/merchant/brands'
      path: '/brands'
      fullPath: '/merchant/brands'
      preLoaderRoute: typeof SiteMerchantBrandsRouteImport
      parentRoute: typeof SiteMerchantRoute
    }
    '/_site/category/$slug': {
      id: '/_site/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof SiteCategorySlugRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/admin/warranties': {
      id: '/_site/admin/warranties'
      path: '/warranties'
      fullPath: '/admin/warranties'
      preLoaderRoute: typeof SiteAdminWarrantiesRouteImport
      parentRoute: typeof SiteAdminRoute
    }
    '/_site/admin/vouchers': {
      id: '/_site/admin/vouchers'
      path: '/vouchers'
      fullPath: '/admin/vouchers'
      preLoaderRoute: typeof SiteAdminVouchersRouteImport
      parentRoute: typeof SiteAdminRoute
    }
    '/_site/admin/users': {
      id: '/_site/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof SiteAdminUsersRouteImport
      parentRoute: typeof SiteAdminRoute
    }
    '/_site/admin/stores': {
      id: '/_site/admin/stores'
      path: '/stores'
      fullPath: '/admin/stores'
      preLoaderRoute: typeof SiteAdminStoresRouteImport
      parentRoute: typeof SiteAdminRoute
    }
    '/_site/admin/stats': {
      id: '/_site/admin/stats'
      path: '/stats'
      fullPath: '/admin/stats'
      preLoaderRoute: typeof SiteAdminStatsRouteImport
      parentRoute: typeof SiteAdminRoute
    }
    '/_site/admin/shippers': {
      id: '/_site/admin/shippers'
      path: '/shippers'
      fullPath: '/admin/shippers'
      preLoaderRoute: typeof SiteAdminShippersRouteImport
      parentRoute: typeof SiteAdminRoute
    }
    '/_site/admin/reviews': {
      id: '/_site/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof SiteAdminReviewsRouteImport
      parentRoute: typeof SiteAdminRoute
    }
    '/_site/admin/products': {
      id: '/_site/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof SiteAdminProductsRouteImport
      parentRoute: typeof SiteAdminRoute
    }
    '/_site/admin/orders': {
      id: '/_site/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof SiteAdminOrdersRouteImport
      parentRoute: typeof SiteAdminRoute
    }
    '/_site/admin/news': {
      id: '/_site/admin/news'
      path: '/news'
      fullPath: '/admin/news'
      preLoaderRoute: typeof SiteAdminNewsRouteImport
      parentRoute: typeof SiteAdminRoute
    }
    '/_site/admin/flash-sales': {
      id: '/_site/admin/flash-sales'
      path: '/flash-sales'
      fullPath: '/admin/flash-sales'
      preLoaderRoute: typeof SiteAdminFlashSalesRouteImport
      parentRoute: typeof SiteAdminRoute
    }
    '/_site/admin/chatbot-history': {
      id: '/_site/admin/chatbot-history'
      path: '/chatbot-history'
      fullPath: '/admin/chatbot-history'
      preLoaderRoute: typeof SiteAdminChatbotHistoryRouteImport
      parentRoute: typeof SiteAdminRoute
    }
    '/_site/admin/categories': {
      id: '/_site/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof SiteAdminCategoriesRouteImport
      parentRoute: typeof SiteAdminRoute
    }
    '/_site/admin/brands': {
      id: '/_site/admin/brands'
      path: '/brands'
      fullPath: '/admin/brands'
      preLoaderRoute: typeof SiteAdminBrandsRouteImport
      parentRoute: typeof SiteAdminRoute
    }
    '/_site/admin/banners': {
      id: '/_site/admin/banners'
      path: '/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof SiteAdminBannersRouteImport
      parentRoute: typeof SiteAdminRoute
    }
    '/_site/account/wishlist': {
      id: '/_site/account/wishlist'
      path: '/wishlist'
      fullPath: '/account/wishlist'
      preLoaderRoute: typeof SiteAccountWishlistRouteImport
      parentRoute: typeof SiteAccountRoute
    }
    '/_site/account/orders': {
      id: '/_site/account/orders'
      path: '/orders'
      fullPath: '/account/orders'
      preLoaderRoute: typeof SiteAccountOrdersRouteImport
      parentRoute: typeof SiteAccountRoute
    }
    '/_site/account/notifications': {
      id: '/_site/account/notifications'
      path: '/notifications'
      fullPath: '/account/notifications'
      preLoaderRoute: typeof SiteAccountNotificationsRouteImport
      parentRoute: typeof SiteAccountRoute
    }
    '/_site/account/addresses': {
      id: '/_site/account/addresses'
      path: '/addresses'
      fullPath: '/account/addresses'
      preLoaderRoute: typeof SiteAccountAddressesRouteImport
      parentRoute: typeof SiteAccountRoute
    }
  }
}

interface SiteAccountRouteChildren {
  SiteAccountAddressesRoute: typeof SiteAccountAddressesRoute
  SiteAccountNotificationsRoute: typeof SiteAccountNotificationsRoute
  SiteAccountOrdersRoute: typeof SiteAccountOrdersRoute
  SiteAccountWishlistRoute: typeof SiteAccountWishlistRoute
  SiteAccountIndexRoute: typeof SiteAccountIndexRoute
}

const SiteAccountRouteChildren: SiteAccountRouteChildren = {
  SiteAccountAddressesRoute: SiteAccountAddressesRoute,
  SiteAccountNotificationsRoute: SiteAccountNotificationsRoute,
  SiteAccountOrdersRoute: SiteAccountOrdersRoute,
  SiteAccountWishlistRoute: SiteAccountWishlistRoute,
  SiteAccountIndexRoute: SiteAccountIndexRoute,
}

const SiteAccountRouteWithChildren = SiteAccountRoute._addFileChildren(
  SiteAccountRouteChildren,
)

interface SiteAdminRouteChildren {
  SiteAdminBannersRoute: typeof SiteAdminBannersRoute
  SiteAdminBrandsRoute: typeof SiteAdminBrandsRoute
  SiteAdminCategoriesRoute: typeof SiteAdminCategoriesRoute
  SiteAdminChatbotHistoryRoute: typeof SiteAdminChatbotHistoryRoute
  SiteAdminFlashSalesRoute: typeof SiteAdminFlashSalesRoute
  SiteAdminNewsRoute: typeof SiteAdminNewsRoute
  SiteAdminOrdersRoute: typeof SiteAdminOrdersRoute
  SiteAdminProductsRoute: typeof SiteAdminProductsRoute
  SiteAdminReviewsRoute: typeof SiteAdminReviewsRoute
  SiteAdminShippersRoute: typeof SiteAdminShippersRoute
  SiteAdminStatsRoute: typeof SiteAdminStatsRoute
  SiteAdminStoresRoute: typeof SiteAdminStoresRoute
  SiteAdminUsersRoute: typeof SiteAdminUsersRoute
  SiteAdminVouchersRoute: typeof SiteAdminVouchersRoute
  SiteAdminWarrantiesRoute: typeof SiteAdminWarrantiesRoute
  SiteAdminIndexRoute: typeof SiteAdminIndexRoute
}

const SiteAdminRouteChildren: SiteAdminRouteChildren = {
  SiteAdminBannersRoute: SiteAdminBannersRoute,
  SiteAdminBrandsRoute: SiteAdminBrandsRoute,
  SiteAdminCategoriesRoute: SiteAdminCategoriesRoute,
  SiteAdminChatbotHistoryRoute: SiteAdminChatbotHistoryRoute,
  SiteAdminFlashSalesRoute: SiteAdminFlashSalesRoute,
  SiteAdminNewsRoute: SiteAdminNewsRoute,
  SiteAdminOrdersRoute: SiteAdminOrdersRoute,
  SiteAdminProductsRoute: SiteAdminProductsRoute,
  SiteAdminReviewsRoute: SiteAdminReviewsRoute,
  SiteAdminShippersRoute: SiteAdminShippersRoute,
  SiteAdminStatsRoute: SiteAdminStatsRoute,
  SiteAdminStoresRoute: SiteAdminStoresRoute,
  SiteAdminUsersRoute: SiteAdminUsersRoute,
  SiteAdminVouchersRoute: SiteAdminVouchersRoute,
  SiteAdminWarrantiesRoute: SiteAdminWarrantiesRoute,
  SiteAdminIndexRoute: SiteAdminIndexRoute,
}

const SiteAdminRouteWithChildren = SiteAdminRoute._addFileChildren(
  SiteAdminRouteChildren,
)

interface SiteMerchantRouteChildren {
  SiteMerchantBrandsRoute: typeof SiteMerchantBrandsRoute
  SiteMerchantCategoriesRoute: typeof SiteMerchantCategoriesRoute
  SiteMerchantDashboardRoute: typeof SiteMerchantDashboardRoute
  SiteMerchantFlashSalesRoute: typeof SiteMerchantFlashSalesRoute
  SiteMerchantInventoryRoute: typeof SiteMerchantInventoryRoute
  SiteMerchantOrdersRoute: typeof SiteMerchantOrdersRoute
  SiteMerchantProductsRoute: typeof SiteMerchantProductsRoute
  SiteMerchantStaffRoute: typeof SiteMerchantStaffRoute
  SiteMerchantVouchersRoute: typeof SiteMerchantVouchersRoute
  SiteMerchantWarrantiesRoute: typeof SiteMerchantWarrantiesRoute
}

const SiteMerchantRouteChildren: SiteMerchantRouteChildren = {
  SiteMerchantBrandsRoute: SiteMerchantBrandsRoute,
  SiteMerchantCategoriesRoute: SiteMerchantCategoriesRoute,
  SiteMerchantDashboardRoute: SiteMerchantDashboardRoute,
  SiteMerchantFlashSalesRoute: SiteMerchantFlashSalesRoute,
  SiteMerchantInventoryRoute: SiteMerchantInventoryRoute,
  SiteMerchantOrdersRoute: SiteMerchantOrdersRoute,
  SiteMerchantProductsRoute: SiteMerchantProductsRoute,
  SiteMerchantStaffRoute: SiteMerchantStaffRoute,
  SiteMerchantVouchersRoute: SiteMerchantVouchersRoute,
  SiteMerchantWarrantiesRoute: SiteMerchantWarrantiesRoute,
}

const SiteMerchantRouteWithChildren = SiteMerchantRoute._addFileChildren(
  SiteMerchantRouteChildren,
)

interface SiteRouteChildren {
  SiteAboutRoute: typeof SiteAboutRoute
  SiteAccountRoute: typeof SiteAccountRouteWithChildren
  SiteAdminRoute: typeof SiteAdminRouteWithChildren
  SiteCartRoute: typeof SiteCartRoute
  SiteCheckoutRoute: typeof SiteCheckoutRoute
  SiteCheckoutSuccessRoute: typeof SiteCheckoutSuccessRoute
  SiteContactRoute: typeof SiteContactRoute
  SiteFlashSaleRoute: typeof SiteFlashSaleRoute
  SiteForgotPasswordRoute: typeof SiteForgotPasswordRoute
  SiteLoginRoute: typeof SiteLoginRoute
  SiteMerchantRoute: typeof SiteMerchantRouteWithChildren
  SiteNewsRoute: typeof SiteNewsRoute
  SitePaymentResultRoute: typeof SitePaymentResultRoute
  SitePromotionsRoute: typeof SitePromotionsRoute
  SiteRegisterRoute: typeof SiteRegisterRoute
  SiteResetPasswordRoute: typeof SiteResetPasswordRoute
  SiteSearchRoute: typeof SiteSearchRoute
  SiteStoresRoute: typeof SiteStoresRoute
  SiteVerifyEmailRoute: typeof SiteVerifyEmailRoute
  SiteIndexRoute: typeof SiteIndexRoute
  SiteCategorySlugRoute: typeof SiteCategorySlugRoute
  SiteNewsIdRoute: typeof SiteNewsIdRoute
  SitePoliciesSlugRoute: typeof SitePoliciesSlugRoute
  SiteProductIdRoute: typeof SiteProductIdRoute
  SiteStoreIdRoute: typeof SiteStoreIdRoute
  SiteTrackOrderOrderIdRoute: typeof SiteTrackOrderOrderIdRoute
  SiteTrackOrderIndexRoute: typeof SiteTrackOrderIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteAboutRoute: SiteAboutRoute,
  SiteAccountRoute: SiteAccountRouteWithChildren,
  SiteAdminRoute: SiteAdminRouteWithChildren,
  SiteCartRoute: SiteCartRoute,
  SiteCheckoutRoute: SiteCheckoutRoute,
  SiteCheckoutSuccessRoute: SiteCheckoutSuccessRoute,
  SiteContactRoute: SiteContactRoute,
  SiteFlashSaleRoute: SiteFlashSaleRoute,
  SiteForgotPasswordRoute: SiteForgotPasswordRoute,
  SiteLoginRoute: SiteLoginRoute,
  SiteMerchantRoute: SiteMerchantRouteWithChildren,
  SiteNewsRoute: SiteNewsRoute,
  SitePaymentResultRoute: SitePaymentResultRoute,
  SitePromotionsRoute: SitePromotionsRoute,
  SiteRegisterRoute: SiteRegisterRoute,
  SiteResetPasswordRoute: SiteResetPasswordRoute,
  SiteSearchRoute: SiteSearchRoute,
  SiteStoresRoute: SiteStoresRoute,
  SiteVerifyEmailRoute: SiteVerifyEmailRoute,
  SiteIndexRoute: SiteIndexRoute,
  SiteCategorySlugRoute: SiteCategorySlugRoute,
  SiteNewsIdRoute: SiteNewsIdRoute,
  SitePoliciesSlugRoute: SitePoliciesSlugRoute,
  SiteProductIdRoute: SiteProductIdRoute,
  SiteStoreIdRoute: SiteStoreIdRoute,
  SiteTrackOrderOrderIdRoute: SiteTrackOrderOrderIdRoute,
  SiteTrackOrderIndexRoute: SiteTrackOrderIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SiteRoute: SiteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
